#!/usr/bin/env bash

#Set keyboard layout
loadkeys be-latin1

#Update the system clock
timedatectl set-ntp true
timedatectl status

#Create partitions
parted /dev/sda mklabel gpt 
parted /dev/sda mkpart primary ext4 1MiB 513MiB 
parted /dev/sda mkpart primary ext4 513MiB 100%  
