#!/usr/bin/env bash

#Set keyboard layout
loadkeys be-latin1

#Update the system clock
timedatectl set-ntp true
timedatectl status

#Create the partitions
parted -s /dev/sda mklabel gpt 
parted -s /dev/sda mkpart primary ext4 1MiB 513MiB 
parted -s /dev/sda mkpart primary ext4 513MiB 100%  

#Format the partitions
mkfs.vfat /dev/sda1
mkfs.ext4 /dev/sda2

#Mount the partitions
mount /dev/sda2 /mnt
mkdir /mnt/boot
mount /dev/sda1 /mnt/boot

#Select mirrors
nano /etc/pacman.d/mirrorlist

#Install the base packages
pacstrap /mnt base

#Generate fstab file
genfstab -U /mnt >> /mnt/etc/fstab
cat /mnt/etc/fstab

#Chroot
arch-chroot /mnt

#Set timezone
ln -sf /usr/share/zoneinfo/Europe/Brussels /etc/localtime
hwclock --systohc

#Set locale
echo "en_US.UTF-8 UTF-8" | tee -a /etc/locale.gen
echo "nl_BE.UTF-8 UTF-8" | tee -a /etc/locale.gen
locale-gen

echo "LANG=nl_BE.UTF-8" | tee /etc/locale.conf
echo "KEYMAP=be-latin1" | tee /etc/vconsole.conf

#Set hostname
echo "home" | tee /etc/hostname
echo "127.0.1.1 home.network.lan  home" | tee -a /etc/hosts

#Set password
passwd

#Install bootloader
pacman -S syslinux gptfdisk mtools
syslinux-install_update -i -a -m
nano /boot/syslinux/syslinux.cfg

exit
reboot

systemctl enable dhcpcd.service
systemctl start dhcpcd.service

useradd -m -s /bin/bash err
passwd err

pacman -S sudo

 export EDITOR=nano
 visudo
 
 err   HOST_NAME=(ALL) ALL
 
 exit
 
 sudo pacman -Syu
 
 -S : Synchronize
 -y : refresh packages
 -u : upgrades
 
 sudo pacman -S xorg-server xorg-xinit xf86-video-fbdev xf86-video-vesa  i3 
 
 





